name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest backend image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/api-zenith-backend:latest

      - name: Pull latest frontend image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/api-zenith-frontend:latest

      - name: Deploy to staging
        run: |
          docker-compose -f docker-compose.staging.yml up -d
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          REDIS_URL: ${{ secrets.STAGING_REDIS_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}
